# Generated by Django 2.2.10 on 2020-02-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula5', '0002_categoria_comentario_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtos', models.ManyToManyField(related_name='carrinho', to='aula5.Produto')),
            ],
        ),
    ]
