# Generated by Django 2.2.10 on 2020-02-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula5', '0003_carrinho_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='valor',
            new_name='preco',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='usuario',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
