# Generated by Django 2.2.10 on 2020-02-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula5', '0004_auto_20200229_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='produtos',
        ),
        migrations.AddField(
            model_name='produto',
            name='carrinho',
            field=models.ManyToManyField(related_name='produtos', to='aula5.Carrinho'),
        ),
    ]
