# Generated by Django 2.2.10 on 2020-02-29 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aula5', '0005_auto_20200229_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='produto',
            name='carrinho',
        ),
        migrations.AddField(
            model_name='produto',
            name='carrinho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aula5.Carrinho'),
            preserve_default=False,
        ),
    ]
