# Generated by Django 2.2.10 on 2020-02-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula5', '0007_auto_20200229_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
